# numpy
* https://numpy.org/
* numpy: Nemerical Python 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 비슷한 자료형
* 순서가 있는 자료형
* 파이썬의 list와의 차이는 자료형이 1가지만 들어간다.

# 차원
* 0차원 = 점. 스칼라 a = 10
* 1차원 = 선 ------ 벡터, 배열, list, tuple [1,2,3,4]
    * 벡터는 방향을 가진 데이터
* 2차원 = 면, 가로, 세로, DB 테이블, DataFrame, matrix
* 3차원 = 입체, 가로, 세로, 깊이, 정육면체
* 4차원 = 3차원 요소가 2개 이상
* 5차원 = 4차원 요소가 2개 이상

In [4]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [6]:
# ndarry는 벡터 이므로 1차원
a.ndim

1

* 차원을 출력하는 메서드 .ndim,
* 차원의 형태를 출력하는 메서드 .shape

In [8]:
# 방향이 없는 벡터
a.shape

(5,)

In [15]:
# 2차원 데이터
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [12]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
c.ndim

2

In [14]:
c.shape

(2, 5)

In [17]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]])

In [18]:
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [19]:
d.ndim

3

In [20]:
d.shape

(2, 2, 5)

In [23]:
# 4차원 데이터
e = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]], [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]])

In [24]:
e

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [25]:
e.ndim

4

In [26]:
e.shape

(2, 2, 2, 5)

In [27]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]], [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]], [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]], [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]]])

In [28]:
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]]])

In [29]:
f.ndim

5

In [30]:
f.shape

(2, 2, 2, 2, 5)

In [33]:
# 세로로 방향을 가진 행벡터
a2 = np.array([[1],[2],[3],[4],[5]])
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [34]:
a2.shape

(5, 1)

# 넘파이를 사용하는 이유
* 행렬 연산이 쉽고 빠르기 때문

In [ ]:
# 스칼라 연산
a = 10
b = 5
scalar = a + b
print(scalar)

In [35]:
# 1차원 데이터 벡터의 연산
b1 = [1,2,3,4,5]
# 리스트의 요소에 10을 곱한 후 다시 리스트로 만드세요.
result = []
for num in b1:
    result.append(num*10)
result

[10, 20, 30, 40, 50]

In [36]:
result2 = [num * 10 for num in b1]
result2

[10, 20, 30, 40, 50]

In [43]:
# 2차원 데이터 계산 * 10 하기
second = np.array([[1,2,3], [1,2,3]])
print(second, second.ndim, second.shape)

[[1 2 3]
 [1 2 3]] 2 (2, 3)


In [56]:
result = []
for num in second:
    mid_result = []
    for number in num:
        mid_result.append(number*10)
    result.append(mid_result)
result = np.array(result)

In [57]:
result.ndim

2

In [49]:
# 3차원 데이터의 요소에 10 곱하기
third = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])
print(third, third.ndim, third.shape)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 3 (2, 2, 3)


In [61]:
result = []
for num1 in third:
    num1_result = []
#     print(num1, end="\n\n")
    for num2 in num1:
        num2_result = []
#         print(num2)
        for num3 in num2:
            num2_result.append(num3*10)
        num1_result.append(num2_result)
    result.append(num1_result)
result = np.array(result)

In [62]:
result.ndim

3

In [63]:
result.shape

(2, 2, 3)

In [66]:
# 4차원 데이터 요소에 10 곱하기
forth = np.array([[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]], [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]])
print(forth.ndim, forth.shape)

4 (2, 2, 2, 3)


In [65]:
forth * 10

array([[[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]],


       [[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]]])

In [67]:
# 5차원 데이터 요소에 10 곱하기
fifth = np.array([[[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]], [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]], [[[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]], [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]]])

In [68]:
fifth * 10

array([[[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]],



       [[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]]])

# numpy에서 자주 사용하는 메서드
* .ndim: 몇차원인지 보는 것
* .shape: 몇 차원, 몇 행, 몇 열로 되어 있는지 구조 확인
* .size: 배열안에 있는 요소의 총 개수가 몇 개인지
* .dtype: 데이터 타입이 무엇인지

In [69]:
fifth.ndim

5

In [70]:
fifth.shape

(2, 2, 2, 2, 3)

In [71]:
fifth.size

48

In [72]:
fifth.dtype

dtype('int64')

# ndarray 만들기
* numpy의 기본 자료형 ndarry
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다.

In [75]:
e = np.array([1,2,3,4,5])
e

array([1, 2, 3, 4, 5])

In [78]:
e2 = np.array((1, 2, 3.14, 4, 5))
print(e2)
e2.dtype

[1.   2.   3.14 4.   5.  ]


dtype('float64')

In [79]:
e3 = np.array((1, 2, 3.14, "4", 5))
print(e3)
e3.dtype

['1' '2' '3.14' '4' '5']


dtype('<U32')

* np.arange(시작, 끝, step)

In [81]:
a = np.arange(1, 11, 2)
a

array([1, 3, 5, 7, 9])

In [82]:
# 1-100까지 있는 array
a3 = np.arange(1, 101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [88]:
# .reshape(행, 열) 벡터를 원하는 크기의 matrix 또는 다차원 배열로 변환
print(a3.ndim)
print(a3.shape)
a4 = a3.reshape(20, 5)
print(a4.ndim)
print(a4.shape)

1
(100,)
2
(20, 5)


In [89]:
a5 = a3.reshape(5, 4, 5)
a5

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [91]:
a6 = a3.reshape(4, 25)
print(a6.ndim)
print(a6.shape)
a6

2
(4, 25)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [92]:
# flatten() : 다차원 배열을 1차원으로 펼쳐줌
a6.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [93]:
a7 = np.arange(24)
a7 = a7.reshape(3,2,2,2)
a7

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [94]:
a7.ndim

4

In [95]:
a7.shape

(3, 2, 2, 2)

In [97]:
a72 = a7.flatten()
a72

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [99]:
a73 = a72.reshape(3,2,2,2)
a73

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [102]:
# np.flip() 행렬의 순서를 뒤집을 때
np.flip(a73)

array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

In [103]:
a73[::-1]

array([[[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]]])

In [104]:
# np.linspace(시작, 끝, 구간 수): 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [106]:
np.linspace(1, 10, 33)

array([ 1.     ,  1.28125,  1.5625 ,  1.84375,  2.125  ,  2.40625,
        2.6875 ,  2.96875,  3.25   ,  3.53125,  3.8125 ,  4.09375,
        4.375  ,  4.65625,  4.9375 ,  5.21875,  5.5    ,  5.78125,
        6.0625 ,  6.34375,  6.625  ,  6.90625,  7.1875 ,  7.46875,
        7.75   ,  8.03125,  8.3125 ,  8.59375,  8.875  ,  9.15625,
        9.4375 ,  9.71875, 10.     ])

In [107]:
np.linspace(1, 10, 539)

array([ 1.        ,  1.01672862,  1.03345725,  1.05018587,  1.0669145 ,
        1.08364312,  1.10037175,  1.11710037,  1.133829  ,  1.15055762,
        1.16728625,  1.18401487,  1.20074349,  1.21747212,  1.23420074,
        1.25092937,  1.26765799,  1.28438662,  1.30111524,  1.31784387,
        1.33457249,  1.35130112,  1.36802974,  1.38475836,  1.40148699,
        1.41821561,  1.43494424,  1.45167286,  1.46840149,  1.48513011,
        1.50185874,  1.51858736,  1.53531599,  1.55204461,  1.56877323,
        1.58550186,  1.60223048,  1.61895911,  1.63568773,  1.65241636,
        1.66914498,  1.68587361,  1.70260223,  1.71933086,  1.73605948,
        1.7527881 ,  1.76951673,  1.78624535,  1.80297398,  1.8197026 ,
        1.83643123,  1.85315985,  1.86988848,  1.8866171 ,  1.90334572,
        1.92007435,  1.93680297,  1.9535316 ,  1.97026022,  1.98698885,
        2.00371747,  2.0204461 ,  2.03717472,  2.05390335,  2.07063197,
        2.08736059,  2.10408922,  2.12081784,  2.13754647,  2.15

In [108]:
# 정렬, .sort(), sorted()
f = np.array([5, 7, 11, 1, 3, 2, 67, 4, 72, 5.3, 21])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 67. ,  4. , 72. ,  5.3, 21. ])

In [ ]:
# axis=-1 가장 안쪽 차원 1차월 배열을 정렬
# np.sort() 함수의 asis 기본값은 -1
# axis=1 세로방향으로 정렬, 2차원 배열에서 각 열을 정렬

In [110]:
f.sort()
f

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  5.3,  7. , 11. , 21. , 67. , 72. ])

In [111]:
f.size

11

In [113]:
f = f.reshape(2,5)
f.sort()
f

ValueError: cannot reshape array of size 11 into shape (2,5)

In [114]:
# argsort() 자료중 값이 작은 것에서 큰 순으로 원래 인덱스 출력
g = np.array([5, 0.5, -7, 42, 10, 0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [ ]:
# 2, 5, 1, 0, 4, 3

In [116]:
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])

In [119]:
g[s][::-1]

array([42. , 10. ,  5. ,  0.5,  0. , -7. ])

* np.where(조건, 참, 거짓) 3항 연산

In [6]:
num = np.arange(1, 11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.where(num % 2 == 0, "짝수", "홀수")

array(['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수'],
      dtype='<U2')

In [8]:
result = []
for i in  num:
    if i % 2 ==0:
        result.append("짝수")
    else:
        result.append("홀수")
result

['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수']

# 배열 합치기 np.concatenate()

In [10]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print(a, a.shape, a.ndim)
print(b, b.shape, b.ndim)

[[1 2]
 [3 4]] (2, 2) 2
[[5 6]
 [7 8]] (2, 2) 2


* np.concatenate((a,b))
* 합치는 기본 방향은 axis=0 행이 늘어남, 아래로 붙음
* axis=1 열이 늘어남, 옆으로 붙음

In [11]:
# axis=0 아래로 늘어나면서 합쳐짐
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# 합치는 방향의 모양이 일치하지 않으면 합치기 X

In [14]:
c = np.array([[5,6]])
print(c, c.ndim, c.shape)

[[5 6]] 2 (1, 2)


In [22]:
# 차원이 맞지 않아서 합쳐지지 않음
np.concatenate((a,c))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
d = np.array([[7,8, 9]])
print(d, d.ndim, d.shape)

[[7 8 9]] 2 (1, 3)


In [18]:
a

array([[1, 2],
       [3, 4]])

In [20]:
d

array([[7, 8, 9]])

In [23]:
np.concatenate((a,d), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [24]:
e = np.array([[1,2,3],[4,5,6]])
print(e, e.ndim, e.shape)

[[1 2 3]
 [4 5 6]] 2 (2, 3)


In [25]:
np.concatenate((d,e), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [27]:
f = np.array([[1,2], [3,4], [5,6]])
print(f, f.ndim, f.shape)

[[1 2]
 [3 4]
 [5 6]] 2 (3, 2)


In [28]:
np.concatenate((e, f))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
# 전치행렬 : 행과 열을 바꿈

In [29]:
np.concatenate((e, f.T), axis=1)

array([[1, 2, 3, 1, 3, 5],
       [4, 5, 6, 2, 4, 6]])

# 전치행렬 만들기
* .T
* .transpose()

# 브로드 캐스팅
* 벡터와 스칼라, 혹은 매트릭스와 벡터를 연산할 때 자동으로 행렬 크기를 맞춰 주는 것

In [33]:
a = np.arange(1, 16).reshape(3, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [34]:
a + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
b = np.array([10, 20, 30, 40, 50])
print(b, b.ndim, b.shape)

[10 20 30 40 50] 1 (5,)
